[gcp_service_account]
type = "service_account"
project_id = "moonlit-buckeye-425823-h7"
private_key_id = "dd201c164af7028a9d8fc3962b98576e40768bc7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCr7wvBr3QhkQSn
drACrov5+OXH+1I+88d0vyCP+HzoxzUaY6vQMLz9hejZ5KQzl+4Pr3ATNt00cEg+
mxV3vLVSXTG38xMhv+QU1YgZodM3bN6gQFZ+Z3A/5wOuID95YuM5i22Iy3aIoutB
xNYxl6F6nacu0Cc2KAZD5z4STOt5zEXDlh5fm/ALXLhanVd0tb4WnIkOnC94X+Ps
kI6H6QufLETBG0xRG/nd5cQsxo2xKa2X7puNM97826vjdM7tqopywARfSZ6dEzDK
c4JrZ1O7cFbhpAt010veSYVi60zCO+btSkXqmQz13mIuoQ/Vm6T5bYXQYNzLRZhk
+XpR9aJdAgMBAAECggEAP76vEy5j1hYYLaZ5d2UTjKhVOSHaynBDoOtDvV0ZooxJ
CfGuP8/yIeTGAhMdNeu8XaBj4xvSQ6DliCCjgvM6HsFir5q1myuz+m14ulgfIUuB
9tQjvVXIbkjOOn7GSdD6AdnJ0I/u8JXGt2mtKFHZksZkt5yBDTklqYNQpiRSoaMX
vmqaJaIX9Vj2T87+3W1c/ij0SIpHnG66Gc0+lG86+tq+vRSFlNX2Pxgyv1nYaYXW
GS8sQZ6d2M1rP4JoIBGdr1zHtOFzjxPGezVRAjLrM0ZeLW5n79kcH987KrK2SEDL
j72EKq4ox3ty6ppiUS8LYmG0CP1EioceUwmfDw4NWQKBgQDvuUk/Ll8rQDs/lNSb
x+wIQV4QR8X4rq3+yUbNZCKEAvxrLa0aQNms1t38DAa4wGw3PAIoJKNu77wMVTNW
bb3mlzy6sJwgcSIif2qCtJmEDWUIlNaVRovr8wA0zM/9l7FbU5wJZG2w7/lOoutW
PxKinZ8U6T4twNJDVzQuD9SBTwKBgQC3m3sIs3qeUox/nN7EWh8L1OLpHX+rxTlh
ZF1IrR9v935TPuYLXJB8jden2dDW0oqu/TFnPeKEfzaiDa4Olp8OgxdThsF21Ufg
OFNbzW+K9okL4ledRCJ+8oVQ5zaAoeFB3WTIDwwzO2S5drVw+sJGrdket0n8xsWW
T6mWbG3+kwKBgHvBcq/cV6MzaKLdSZkWb6KfZFkRRIGqZAbZj+Suoib2h6spDGk2
O2nADx90ce/k3rjxEMf6iijWOIVBYtxmkRe+0corLJ6O6SlYD/tkErCaXaM9ez3b
CpcHfv7DEUkAi73y/uXWY85pRJI1BzsiGpO6vYqFEuV52tKK7VQuNe1/AoGBAKQj
nw3cRZYb/fZnas7mMjMFkgUMlgIdQnrKmopKGnyiKJCK/mTRz2lJ9KzdkFE7zzc4
ql29eS8x+slMqXnpNTBoCQZmxbVSXfsY34yGT11PoJy7L9AsBRqv/Hai/JpqHVIg
deRTb3itdBJJCVODGQLOj/dhrAcKO8FwXg9Xx815AoGAKNACm45/9mMhHoLKCeAg
SZFagmQKV8s1pHmOK1QXbvgwOo/YCvp6veL3kdCDZ/6a4FS4CH6qvPXTsIpGYpLw
5kcmmSSkpOApKoMK8TSG+fkytKA2H5Zhjx7R0rtCYV33R7IaCk07RBidU+Saij23
vwrO7qQpnQD6qRbLIgn8ZeY=
-----END PRIVATE KEY-----"""
client_email = "udemy-741@moonlit-buckeye-425823-h7.iam.gserviceaccount.com"
client_id = "105266914558421378207"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/udemy-741%40moonlit-buckeye-425823-h7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"